fail_fast: false

default_language_version:
  python: python3.12

repos:
  # Base
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  # Black
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  # Isort
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

    # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff

  # Typos
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.23
    hooks:
      - id: typos

#  # Pytest
#  - repo: local
#    hooks:
#      - id: tests
#        name: run tests
#        entry: pytest -v
#        language: system
#        always_run: true
#        types: [ python ]
#        stages: [ commit ]
