version: "3.9"

services:
  database:
      container_name: users.database
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        PGDATA: ${POSTGRES_PGDATA}
      ports:
        - ${POSTGRES_PORT}:5432
      volumes:
        - ${POSTGRES_PGDATA}
      env_file:
        - .env
