[api]
host = '0.0.0.0'
port = 1337
debug = false

[database]
host = "database"
port = 5432
password = "postgres"
user = "postgres"
dbname = "postgres"

[jwt]
algorithm = "RS256"
access_token_expire_minutes = 60
refresh_token_expire_minutes = 43200
