[server]
host = '127.0.0.1'
port = 8000
log_level = "DEBUG"
json_format = false

[database]
host = "localhost"
port = 5432
password = "postgres"
user = "postgres"
dbname = "postgres"

[jwt]
algorithm = "RS256"
access_token_expire_minutes = 60
refresh_token_expire_minutes = 43200

[app]
debug = true
title = "User service"
version = "1.0.0"
local = true
doc_url = "/docs"
openapi_url = "/openapi.json"
redoc_url = "/redoc"
doc_password = "admin"
doc_username = "admin"
origins = ["*"]

[logging]
level = "DEBUG"
json_format = false
